### ISSUE TITLE
你好楼主，我把你的项目运行起来后视频裁剪，点击完成提示处理中，然后就没了，完成按钮变灰，等了好久也没有处理成功提示

### ISSUE THREAD

**Issue by daijunsheng** [yangyong915/AlbumSelectionManager#2]
你好楼主，我把你的项目运行起来后视频裁剪，点击完成提示处理中，然后就没了，完成按钮变灰，等了好久也没有处理成功提示

**Comment by whoislxy** [comment]
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at java.io.File.fixSlashes(File.java:195)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at java.io.File.<init>(File.java:144)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at com.mabeijianxi.smallvideorecord2.LocalMediaCompress.startCompress(LocalMediaCompress.java:195)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at com.luck.picture.lib.PicturePreviewActivity.getVideoLocalMedias(PicturePreviewActivity.java:812)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at com.luck.picture.lib.PicturePreviewActivity.access$1500(PicturePreviewActivity.java:77)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at com.luck.picture.lib.PicturePreviewActivity$6.apply(PicturePreviewActivity.java:752)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at com.luck.picture.lib.PicturePreviewActivity$6.apply(PicturePreviewActivity.java:749)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:58)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:246)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10685)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10685)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
04-10 22:35:10.440 12841-12841/com.electric.chargingpile W/System.err:     at io.reactivex.Scheduler$1.run(Scheduler.java:134)
04-10 22:35:10.450 12841-12841/com.electric.chargingpile W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
04-10 22:35:10.450 12841-12841/com.electric.chargingpile W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
04-10 22:35:10.450 12841-12841/com.electric.chargingpile W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-10 22:35:10.450 12841-12841/com.electric.chargingpile W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
04-10 22:35:10.450 12841-12841/com.electric.chargingpile W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
04-10 22:35:10.450 12841-12841/com.electric.chargingpile W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-10 22:35:10.450 12841-12841/com.electric.chargingpile W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-10 22:35:10.450 12841-12841/com.electric.chargingpile W/System.err:     at java.lang.Thread.run(Thread.java:831)

**Comment by whoislxy** [comment]
贴上错误

**Comment by LeonFangCN** [comment]
看了下代码,JianXiCamera里面public static void setVideoCachePath(String path)先调用设置一下路径就行了

**Comment by LeonFangCN** [comment]
JianXiCamera第24行改为
 private static String mVideoCachePath= Environment.getExternalStorageDirectory().getAbsolutePath() + "/mio/compressed/";
